#!/bin/bash

#########THIS part is for Nagios ################################
PROGNAME=`/usr/bin/basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
. $PROGPATH/utils.sh

#####################################################################

#Function to print Usage
function usage
{
echo "Usage: $0 -i [image] -t [registry tag]"
exit $STATE_UNKNOWN
}


IMAGE=alpine:3.7
REGISTRY=registry.registry.svc/monitoring/alpine:3.7
#####################################################################
# get parameter values in Variables

while test -n "$1"; do
    case "$1" in
         -h)
            usage
            ;;
         -i)
            IMAGE=$2
            shift
            ;;
         -t)
            REGISTRY=$2
            shift
            ;;
         *)
            echo "Unknown argument: $1"
            usage
            ;;
    esac
    shift
done



timeout 2 docker version > /dev/null
if [ $? -ne 0 ]; then
        echo "[CRIT] docker version failed"
        exit $STATE_CRITICAL
fi

timeout 20 docker pull $IMAGE > /dev/null
if [ $? -ne 0 ]; then
        echo "[CRIT] docker pull failed"
        exit $STATE_CRITICAL
fi

timeout 2 docker tag $IMAGE $REGISTRY > /dev/null
if [ $? -ne 0 ]; then
        echo "[CRIT] docker tag failed"
        exit $STATE_CRITICAL
fi

timeout 20 docker push $REGISTRY > /dev/null
if [ $? -ne 0 ]; then
        echo "[CRIT] docker push failed"
        exit $STATE_CRITICAL
fi

echo "[OK] - docker pull, tag, push to registry succeeded"
exit $STATE_OK
