#! /bin/bash

#This Plug-in monitors the Unreachable nodes in Cassandra Ring; using nodetool ring command

# Author - Juned Memon



#########THIS part is for Nagios ################################
PROGNAME=`/usr/bin/basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION=`echo '$Revision: 1749 $' | sed -e 's/[^0-9.]//g'`
. $PROGPATH/utils.sh

######################################################################

#Function to print Usage
function usage
{
echo "Usage: $0 -H <HOST> -P <PORT>"
exit $STATE_UNKNOWN
}


HOST="localhost"
PORT=2379
#####################################################################
# get parameter values in Variables

while test -n "$1"; do
    case "$1" in
         -h)
            usage
            ;;
         -H)
            HOST=$2
            shift
            ;;
         -P)
            PORT=$2
            shift
            ;;
         *)
            echo "Unknown argument: $1"
            usage
            ;;
    esac
    shift
done

#####################################################################

STATUS=$( curl -s --cacert /etc/etcd/cert/ca.pem --cert /etc/etcd/cert/client.pem --key /etc/etcd/cert/client-key.pem https://$HOST:$PORT/health )

if [ "$STATUS" == "" ]; then
        echo "[CRIT] $HOST is not answering"
        exit $STATE_CRITICAL
fi

HEALTH_STATE=$( echo "$STATUS" | awk -F '"' '{print $4}' )

if [ "$HEALTH_STATE" == "true" ]; then
        echo "[OK] $HOST is healthy"
        exit $STATE_OK
fi

echo "[CRITICAL] $HOST is unhealthy"
exit $STATE_CRITICAL
