#! /bin/bash

#########THIS part is for Nagios ################################
PROGNAME=`/usr/bin/basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION=`echo '$Revision: 1749 $' | sed -e 's/[^0-9.]//g'`
. $PROGPATH/utils.sh

#####################################################################

#Function to print Usage
function usage
{
echo "Usage: $0 -s [apiserver endpoint] -r [not running warning] -R [not running critical] -i [incomplete warning] -I [incomplete critical]"
exit $STATE_UNKNOWN
}

NOT_RUNNING_WARN=1
NOT_RUNNING_CRIT=2
INCOMPLETE_WARN=1
INCOMPLETE_CRIT=2
APISERVER=https://kubernetes.default.svc
#####################################################################
# get parameter values in Variables

while test -n "$1"; do
    case "$1" in
         -h)
            usage
            ;;
         -r)
            NOT_RUNNING_WARN=$2
            shift
            ;;
         -R)
            NOT_RUNNING_CRIT=$2
            shift
            ;;
         -i)
            INCOMPLETE_WARN=$2
            shift
            ;;
         -I)
            INCOMPLETE_CRIT=$2
            shift
            ;;
         -s)
            APISERVER=$2
            shift
            ;;
         *)
            echo "Unknown argument: $1"
            usage
            ;;
    esac
    shift
done

#####################################################################

TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
KUBECTL="kubectl --server $APISERVER --token $TOKEN --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt"


STATUS=$( $KUBECTL version )
if [ "$STATUS" == "" ]; then
        echo "[UNKNOWN] no answer"
        exit $STATE_UNKNOWN
fi

ALL_PODS=$( $KUBECTL --all-namespaces=true get po --no-headers=true )

NOT_RUNNING=$( echo "$ALL_PODS" | grep -v Running | grep -v Running | grep -v Terminating | grep -v ContainerCreating | wc -l )
if [ "$NOT_RUNNING" -ge "$NOT_RUNNING_WARN" ]; then
	echo "[WARN] $NOT_RUNNING pods are not running"
	exit $STATE_WARNING
fi
if [ "$NOT_RUNNING" -ge "$NOT_RUNNING_CRIT" ]; then
	echo "[CRIT] $NOT_RUNNING pods are not running"
	exit $STATE_CRITICAL
fi

INCOMPLETE_PODS=$( echo "$ALL_PODS" | grep Running | awk -F ' ' '{print $3}' | awk -F / '{  print ($1 == $2) ? "full" : "incomplete" }' | grep incomplete | wc -l )
if [ "$INCOMPLETE_PODS" -ge "$INCOMPLETE_WARN" ]; then
	echo "[CRIT] $INCOMPLETE_PODS pods are in a incomplete state"
	exit $STATE_WARNING
fi
if [ "$INCOMPLETE_PODS" -ge "$INCOMPLETE_CRIT" ]; then
	echo "[CRIT] $INCOMPLETE_PODS pods are in a incomplete state"
	exit $STATE_CRITICAL
fi

echo "[OK] all pods look healthy"
exit $STATE_OK
