name: Test build Docker image

on:
  push:
    branches-ignore:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  client-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@3a3bb3a81753dc99f090d24ee7e5343838b73a96 # renovate: tag=v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/client

      - name: Build Docker image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # renovate: tag=v2
        with:
          context: client
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  server-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@3a3bb3a81753dc99f090d24ee7e5343838b73a96 # renovate: tag=v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/server

      - name: Build Docker image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # renovate: tag=v2
        with:
          context: server
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}